---
- name: Download Helm
  get_url:
    url: "{{ helm_src }}"
    dest: "{{ helm_dest }}"

- name: Extract Helm Archive
  unarchive:
    src: "{{ helm_dest }}"
    dest: "{{ helm_extract_dest }}"
    remote_src: yes

- name: Move Helm Binary to /usr/bin
  copy:
    src: "{{ helm_binary_src }}"
    dest: "{{ helm_binary_dest }}"
    mode: '0755'
    remote_src: yes
